export const QUERY_KEYS = {
  GET_HOTEL_DETAIL: "QUERY_GET_HOTEL_DETAIL",
  GET_ROOMS: "QUERY_GET_ROOMS",
  GET_SPECIFIC_ROOM: "QUERY_GET_SPECIFIC_ROOM",
  GET_HOT_HOTEL: "QUERY_GET_HOT_HOTEL",
  GET_PICTURE: "QUERY_GET_PICTURE",
  GET_REVIEW: "QUERY_GET_REVIEW",
  GET_WEEKLY_REVENUE: "QUERY_GET_WEEKLY_REVENUE",
  GET_YEARLY_REVENUE: "QUERY_GET_YEARLY_REVENUE",
};
