export const bannerData = [
  {
    id: "home-banner@1",
    src: "https://aldortio.sirv.com/sc/banners/book%20now.png",
  },
  {
    id: "home-banner@2",
    src: "https://aldortio.sirv.com/sc/banners/book%20now%20(1).png",
  },
  {
    id: "home-banner@3",
    src: "https://aldortio.sirv.com/sc/banners/book%20now%20(2).png",
  },
];

export const countriesData = [
  "Hà Nội",
  "Hồ Chí Minh",
  "Hà Giang",
  "Cao Bằng",
  "Lai Châu",
  "Lào Cai",
  "Tuyên Quang",
  "Điện Biên",
  "Lạng Sơn",
  "Quảng Ninh",
  "Bắc Giang",
  "Phú Thọ",
  "Vĩnh Phúc",
  "Bắc Ninh",
  "Hải Dương",
  "Hải Phòng",
  "Hưng Yên",
  "Thái Bình",
  "Hà Nam",
  "Nam Định",
  "Ninh Bình",
  "Thanh Hóa",
  "Nghệ An",
  "Hà Tĩnh",
  "Quảng Bình",
  "Quảng Trị",
  "Thanh Hóa",
  "Nghệ An",
  "Hà Tĩnh",
  "Quảng Bình",
  "Quảng Trị",
  "Thanh Hóa",
  "Nghệ An",
  "Hà Tĩnh",
  "Quảng Bình",
  "Quảng Trị",
  "Thanh Hóa",
  "Nghệ An",
  "Hà Tĩnh",
  "Quảng Bình",
  "Quảng Trị",
  "Thanh Hóa",
  "Nghệ An",
  "Hà Tĩnh",
  "Quảng Bình",
  "Quảng Trị",
  "Huế",
  "Đà Nẵng",
  "Quảng Nam",
  "Quảng Ngãi",
  "Bình Định",
  "Phú Yên",
  "Khánh Hòa",
  "Ninh Thuận",
  "Bình Thuận",
  "Kon Tum",
  "Gia Lai",
  "Đắk Lắk",
  "Đắk Nông",
  "Lâm Đồng",
  "Bà Rịa-Vũng Tàu",
  "Bình Dương",
  "Bình Phước",
  "Tây Ninh",
  "Bến Tre",
  "Trà Vinh",
  "Vĩnh Long",
  "Đồng Tháp",
  "An Giang",
  "Kiên Giang",
  "Cần Thơ",
  "Hậu Giang",
  "Sóc Trăng",
  "Bạc Liêu",
  "Cà Mau",
];

// export const countriesData = [
// {
//   Country: "Việt Nam",
//   Province: [
//     "Hà Nội",
//     "Hồ Chí Minh",
//     "Hà Giang",
//     "Cao Bằng",
//     "Lai Châu",
//     "Lào Cai",
//     "Tuyên Quang",
//     "Điện Biên",
//     "Lạng Sơn",
//     "Quảng Ninh",
//     "Bắc Giang",
//     "Phú Thọ",
//     "Vĩnh Phúc",
//     "Bắc Ninh",
//     "Hải Dương",
//     "Hải Phòng",
//     "Hưng Yên",
//     "Thái Bình",
//     "Hà Nam",
//     "Nam Định",
//     "Ninh Bình",
//     "Thanh Hóa",
//     "Nghệ An",
//     "Hà Tĩnh",
//     "Quảng Bình",
//     "Quảng Trị",
//     "Thanh Hóa",
//     "Nghệ An",
//     "Hà Tĩnh",
//     "Quảng Bình",
//     "Quảng Trị",
//     "Thanh Hóa",
//     "Nghệ An",
//     "Hà Tĩnh",
//     "Quảng Bình",
//     "Quảng Trị",
//     "Thanh Hóa",
//     "Nghệ An",
//     "Hà Tĩnh",
//     "Quảng Bình",
//     "Quảng Trị",
//     "Thanh Hóa",
//     "Nghệ An",
//     "Hà Tĩnh",
//     "Quảng Bình",
//     "Quảng Trị",
//     "Huế",
//     "Đà Nẵng",
//     "Quảng Nam",
//     "Quảng Ngãi",
//     "Bình Định",
//     "Phú Yên",
//     "Khánh Hòa",
//     "Ninh Thuận",
//     "Bình Thuận",
//     "Kon Tum",
//     "Gia Lai",
//     "Đắk Lắk",
//     "Đắk Nông",
//     "Lâm Đồng",
//     "Bà Rịa-Vũng Tàu",
//     "Bình Dương",
//     "Bình Phước",
//     "Tây Ninh",
//     "Bến Tre",
//     "Trà Vinh",
//     "Vĩnh Long",
//     "Đồng Tháp",
//     "An Giang",
//     "Kiên Giang",
//     "Cần Thơ",
//     "Hậu Giang",
//     "Sóc Trăng",
//     "Bạc Liêu",
//     "Cà Mau",
//   ],
// },
// {
//   Country: "Korea",
//   Province: [
//     "Seoul",
//     "Busan",
//     "Incheon",
//     "Daegu",
//     "Daejeon",
//     "Gwangju",
//     "Ulsan",
//     "Sejong",
//     "Gyeonggi",
//     "Gangwon",
//     "Chungbuk",
//     "Chungnam",
//     "Jeonbuk",
//     "Jeonnam",
//     "Gyeongbuk",
//     "Gyeongnam",
//     "Jeju",
//   ],
// },
// {
//   Country: "Japan",
//   Province: [
//     "Tokyo",
//     "Osaka",
//     "Kyoto",
//     "Hokkaido",
//     "Aichi",
//     "Fukuoka",
//     "Kanagawa",
//     "Hyogo",
//     "Hiroshima",
//     "Shizuoka",
//     "Chiba",
//     "Saitama",
//     "Ibaraki",
//     "Kumamoto",
//     "Miyagi",
//     "Niigata",
//     "Okayama",
//     "Okinawa",
//     "Gifu",
//     "Mie",
//   ],
// },
// {
//   Country: "Singapore",
//   Province: [
//     "Central Region",
//     "East Region",
//     "North Region",
//     "Northeast Region",
//     "West Region",
//   ],
// },
// {
//   Country: "Australia",
//   Province: [
//     "New South Wales",
//     "Victoria",
//     "Queensland",
//     "Western Australia",
//     "South Australia",
//     "Tasmania",
//     "Australian Capital Territory",
//     "Northern Territory",
//   ],
// },
// {
//   Country: "China",
//   Province: [
//     "Beijing",
//     "Shanghai",
//     "Guangzhou",
//     "Shenzhen",
//     "Chengdu",
//     "Chongqing",
//     "Hangzhou",
//     "Xi'an",
//     "Nanjing",
//     "Tianjin",
//     "Suzhou",
//     "Wuhan",
//   ],
// },
// ];

export const roomTypesData = [
  "Phòng tiêu chuẩn", // Standard Room
  "Phòng sang trọng", // Deluxe Room
  "Phòng suite", // Suite
  "Phòng suite cao cấp", // Junior Suite
  "Phòng suite điều hành", // Executive Suite
  "Căn hộ", // Apartment
  "Biệt thự", // Villa
  "Nhà gỗ", // Bungalow
  "Căn hộ cao cấp", // Penthouse
  "Phòng liền kề", // Connecting Room
  "Phòng kết nối", // Adjoining Room
  "Phòng gia đình", // Family Room
  "Phòng duplex", // Duplex Room
  "Phòng studio", // Studio
  "Phòng loft", // Loft
  "Phòng suite tổng thống", // Presidential Suite
];
