
export const LOCAL_STORAGE_KEY = {
  CART_ADDRESS: "LOCAL_STORAGE_KEY_CART_ADDRESS"
};
export const CONTEXT_ACTION = {
  GET_ACTION: "CONTEXT_ACTION_GET_CART",
  SET_CART_ACTION: "CONTEXT_ACTION_SET_CART_CART",
  SET_TOKEN_ACTION: "CONTEXT_ACTION_SET_TOKEN_CART",
  ADD_ACTION: "CONTEXT_ACTION_ADD_TO_CART",
  UPDATE_ACTION: "CONTEXT_ACTION_UPDATE_CART",
  DELETE_ACTION: "CONTEXT_ACTION_DELETE_CART",
};
export const MUTATION = {
  RETRY_TIMES: 0
};
export const QUERY_KEYS = {
  GET_CART: "QUERY_KEYS_GET_CART"
}