export const QUERY_KEYS = {
  GET_HOTEL_DETAIL: "QUERY_GET_HOTEL_DETAIL",
  GET_ROOMS: "QUERY_GET_ROOMS",
  GET_SPECIFIC_ROOM: "QUERY_GET_SPECIFIC_ROOM",
  GET_HOT_HOTEL: "QUERY_GET_HOT_HOTEL",
  GET_PICTURE: "QUERY_GET_PICTURE",
};
